Several improvements:
gabrielmittag/NISQA pull request #13
Opened 2021-08-18 10:51 UTC by jr2804

- used relative import, in case NISQA is used as a sub-module in an existing project
- nisqaModel.predict(self) returns the dataframe for further usage in Python w/o reading CSV
- In case the input wave/flac-file has more than one channel, the corresponding channel index has to be added to the parameters.
- modified: librosa.load(..., mono=False) -> if input file has more than 1 channel

2021-09-03 00:20 UTC, gabrielmittag requested changes
Hi Jan, 

Thanks for these improvements! I think they're good. Could you just change:

` self.args['n_channel'] = args_new['n_channel']` in line 1033 to

```
        if 'n_channel' in args_new:
            self.args['n_channel'] = args_new['n_channel']
        else:
            self.args['n_channel'] = 0
```
so that this n_channel argument is optional? Otherwise run_predict.py won't work properly anymore.

2021-09-03 00:20 UTC, gabrielmittag commented on nisqa/NISQA_model.py
> +        self.args['n_channel'] = args_new['n_channel']
```suggestion
        if 'n_channel' in args_new:
            self.args['n_channel'] = args_new['n_channel']
        else:
            self.args['n_channel'] = 0
```

2021-09-07 11:39 UTC, jr2804 commented
A very minor and very slightly different change :-)

2021-12-30 18:02 UTC, gabrielmittag commented
Sorry for the late response but I will probably need to make some smaller adjustments so it works with predicting and training. I'll just merge it for now. Thank you! :)

2021-12-30 18:02 UTC, merged